### ISSUE TITLE
Check.blizz.fields only detects the first missing field.

### ISSUE THREAD

**Issue by gergf** [joerg-schneider/blizz#1]
First of all, thanks for this awesome library!! It is amazing to have this tool for free  🚀 

**Issue**
Check.blizz.fields only raises the first missing field, even if there are more. 

I do not know whether this is on purpose or not, but I'd expect the function to detect all missing fields.

Below a reproducible snippet code.  

```
import pandas as pd

import blizz.check
from blizz import Relation, Field


class foo(Relation):
    x = Field("x")
    y = Field("y")
    z = Field("z")

    def __init__():
        super().__init__()

    @classmethod
    @blizz.check.fields(on_fail=blizz.check.WARN)
    def load(cls):
        return pd.DataFrame({"x": [1]})


foo.load()
```

Shell result:
```
>>> .../python3.8/site-packages/blizz/_check.py:189: UserWarning: ValueError("Field 'y' is not part of loaded Relation 'foo'.")
  warnings.warn(error.__repr__())
```

**Comment by joerg-schneider** [comment]
Thanks @gergf – should be covered now by https://github.com/joerg-schneider/blizz/commit/d70ee069b2765a70286f2413f5624c4a2af9af1a

**Comment by gergf** [comment]
LGTM!! I guess we can close now as the commit is directly to master -- thanks @joerg-schneider !!
